---
name: Tomás Capretto
#surname: Capretto
position: "Doctorate Candidate"
address: "IMASL/CONICET"
www: tcapretto.netlify.com
github: tomicapretto
email: "tomicapretto@gmail.com"
aboutme: "Statistician interested in R, Python, R Shiny and anything that helps to make data analysis more pleasant"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "34495e"
output: 
  vitae::awesomecv:
    keep_tex: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Education

```{r education}
tribble(
  ~ degree, ~ dates, ~ uni, ~ where, ~ details,
  "Doctorate in Statistics", "2019-2024 (expected)", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
  paste(
    "I work under the supervision of PhD. Osvaldo Martin on Bayesian statistics",
    "and exploratory data analysis."
  ),
  "Doctorate in Statistics", "2019-2024 (expected)", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
  paste(
    "My goal is to create tools to help practitioners to understand and apply",
    "statistical methods and data analysis techniques with more ease."
  ),
  "Bachelor in Statistics", "2014-2019", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
  paste(
    "The career gave me a solid background in foundations of statistics",
    "as well as the ability to interpret results in an analytical manner."
  ) 
) %>% 
  detailed_entries(degree, dates, uni, where, details)
```

# Research experience

```{r research-experience}

tribble(
  ~ role, ~ date, ~ institution, ~ where, ~ details,
  "Research assistant", "Apr 2018 - Mar 2019", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", "\\textbf{Project:} Statistical methods in official statistics.", 
  
  "Research assistant", "Apr 2018 - Mar 2019", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
  "Wrote my undergraduate thesis \\textit{Estimation in complex survey samples in presence of nonresponse} under the supervision of MSc. Gonzalo Marí.",
  
  "Research assistant", "Apr 2016 - Mar 2017", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
  "\\textbf{Project:} Sampling designs based on models for populations with spatial variability.", 
  "Research assistant", "Apr 2016 - Mar 2017", "Universidad Nacional de Rosario", 
  "Rosario, Argentina", 
   "As a complement of a course in sampling techniques, I dedicated most of the time to the study of new sampling methods that incorporate spatial variability." 
) %>%
  detailed_entries(role, date, institution, where, details, .protect = FALSE)
```


# Work experience

```{r work-experience}

tribble(
  ~ role, ~ date, ~ company, ~ where, ~ details,
  
  "Consultant", "Nov 2018 - Jan 2019", "AlixPartners", "Buenos Aires, Argentina", "Data manipulation and analysis using R, Python, SQL and Tableau.", 
  "Consultant", "Nov 2018 - Jan 2019", "AlixPartners", "Buenos Aires, Argentina", "Time series forecasting.",
  "Consultant", "Nov 2018 - Jan 2019", "AlixPartners", "Buenos Aires, Argentina", "Task automation.", 
  
  "Statistical assistant", "May 2018 - Oct 2018", "Instituto Nacional de Estadística y Censos", "Buenos Aires, Argentina", "I worked on the study of non-response, its classification and treatment.", 
  "Statistical assistant", "May 2018 - Oct 2018", "Instituto Nacional de Estadística y Censos", "Buenos Aires, Argentina", "Contributed to methodological manuals and internal reports.", 
  "Statistical assistant", "May 2018 - Oct 2018", "Instituto Nacional de Estadística y Censos", "Buenos Aires, Argentina", "Evaluation of methods to impute missing data.", 
  
  "Statistical assistant", "Jul 2016 - Sep 2016", "Universidad Nacional de Rosario", "Rosario, Argentina", "Survey sampling study to study characteristics of members from a professional college in Santa Fe province.",
  "Statistical assistant", "Jul 2016 - Sep 2016", "Universidad Nacional de Rosario", "Rosario, Argentina", "Participated in the strategy to collect the data.",
  "Statistical assistant", "Jul 2016 - Sep 2016", "Universidad Nacional de Rosario", "Rosario, Argentina", "Worked on the consistency of the data bases and the generation of internal reports.",
  "Statistical assistant", "Jul 2016 - Sep 2016", "Universidad Nacional de Rosario", "Rosario, Argentina", "Worked on telephone surveys and cases follow-up.",
  
) %>%
  detailed_entries(role, date, company, where, details, .protect = FALSE) # Enables Latex code.
```


\pagebreak

# Training experience

```{r teaching-experience}

tribble(
  ~ role, ~ date, ~ company, ~ where, ~ details,
  
  "Online tutor", "Aug 2018 - May 2019", "Chegg Tutors", "Remote", "Tutored Statistics, R and SAS Programming, and related topics in English.",
  "Online tutor", "Aug 2018 - May 2019", "Chegg Tutors", "Remote", "I worekd with both undergraduate and graduate students from a very wide range of disciplines.",

  "Online tutor", "Nov 2015 - Nov 2018", "Latinhire", "Remote", "Tutored Statistics both in English and Spanish.",
  "Online tutor", "Nov 2015 - Nov 2018", "Latinhire", "Remote", "Worked with both high-school and undergraduate students.",

) %>%
  detailed_entries(role, date, company, where, details, .protect = FALSE) # Enables Latex code.

```


# Software development

All of my public software develpment can be found in my [github profile](github.com/tomicapretto).

## Python

```{r python-pkgs}
tribble(
  ~ pkg, ~ when, ~ role, ~ details,
  "ArviZ", "2020 - ", "Contributor", "A package for exploratory analysis of Bayesian models.",
  "Bambi", "2020 - ", "Contributor", "A a high-level Bayesian model-building interface.",
  "formulae", "2020 - ", "Author", "A WIP library that implements model formulas as in R lme4 package."
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <role> \\newline <details>", .open = "<", .close = ">"), when, .protect = FALSE)
```


## R

```{r r-pkgs}
tribble(
  ~ pkg, ~ when, ~ role, ~ details,
  "latex2r", "2020 - ", "Author", "Translate math formulas written in LaTeX to R code.",
  "shinymath", "2020 - ", "Author", "A new mathematical input for Shiny apps.",
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <role> \\newline <details>", .open = "<", .close = ">"), when, .protect = FALSE)
```

## R Shiny

```{r r-shiny}
tribble(
  ~ pkg, ~ when, ~ role, ~ details,
  "samp", "2021", "Author", "Visualize sampling distributions of several statistics generated from arbitrary mixtures of probability distributions.",
  "ifuns", "2021", "Author", "Interactively tune and visualize univariate mathematical functions.",
  "sdeshiny", "2020", "Author", "An interface for a system of differential equations solver.",
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <role> \\newline <details>", .open = "<", .close = ">"), when, .protect = FALSE)
```


# Scholarships, awards and distinctions

```{r awards}

tribble(
  ~ what, ~ date, ~ institution, ~ place, ~ details,
  
  "Doctorate scholarship in strategic topics", "2019 - 2024", "CONICET", "San Luis, Argentina", "\\textbf{Topic:} Exploratory analysis of Bayesian methods.",
  "Doctorate scholarship in strategic topics", "2019 - 2024", "CONICET", "San Luis, Argentina", "Full-time position dedicated to study and research.",
  
  "1st Prize in the XIII Young Biometrists Contest", "Oct 2017", "Grupo Argentino de Biometría", "Rosario, Argentina", "I worked with David Presutti, Agronomic Engineering student.", 
  "1st Prize in the XIII Young Biometrists Contest", "Oct 2017", "Grupo Argentino de Biometría", "Rosario, Argentina", "We used generalized mixed linear models to solve the proposed problem.", 
  
  "Fulbright scholar", "Jan 2017 - Feb 2017", "Comisión Fulbright Argentina", "Austin, United States", "I made a stay in the  University of Texas at Austin thanks to the scholarship Friends of Fulbright 2017.", 
  "Fulbright scholar", "Jan 2017 - Feb 2017", "Comisión Fulbright Argentina", "Austin, United States", "The activities involved english training, cultural exchange, volunteering and I also attended classes in Statistics.", 
  
) %>% 
  detailed_entries(what, date, institution, place, details, .protect = FALSE)
```

