---
name: Tomás Capretto
#surname: Capretto
position: "Statistician"
www: tomicapretto.github.io
github: tomicapretto
email: "tomicapretto@gmail.com"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "34495e"
output: 
  vitae::awesomecv:
    keep_tex: false
---

\newcommand{\pkg}[1]{{\fontseries{b}\selectfont #1}}
\let\proglang=\textsf

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(readr)
library(tibble)
library(vitae)

data_path <- here::here("cv-english", "data")
```

# Education

```{r education}
read_csv(file.path(data_path, "educacion.csv")) %>% 
  detailed_entries(grado, fecha, institucion, lugar, detalles, .protect = FALSE)
```

# Work experience

```{r work-experience}
d = read_csv(file.path(data_path, "laboral.csv"))
head(d, nrow(d) - 2) %>%
  detailed_entries(posicion, fecha, compania, lugar, detalles, .protect = FALSE)
```

# Skills

```{r habilidades}
read_csv(file.path(data_path, "habilidades.csv")) %>%
  tidyr::replace_na(list(posicion = " ", fecha = " ", que = " ")) %>%
  detailed_entries(posicion, fecha, institucion, que, detalles, .protect = FALSE)
```

<!-- # Research experience -->
<!-- ```{r research-experience} -->
<!-- read_csv(here::here("cv-english/investigacion.csv")) %>% -->
<!--   detailed_entries(posicion, fecha, institucion, lugar, detalles, .protect = FALSE) -->
<!-- ``` -->

\pagebreak

# Software

Almost all of my activity in software development is on my 
\href{https://github.com/tomicapretto}{\underline{Github profile}}. Below I 
include some of the projects that stand out the most or that I most enjoyed doing. 
By clicking on the name of the project you go to the repository.

## Python

```{r r-pkgs}
read_csv(file.path(data_path, "python.csv")) %>%
  tidyr::replace_na(list(fecha = " ", que = " ")) %>%
  detailed_entries(posicion, fecha, institucion, que, detalles, .protect = FALSE)
```

## R

```{r shiny}
read_csv(file.path(data_path, "r.csv")) %>%
  tidyr::replace_na(list(fecha = " ", que = " ")) %>%
  detailed_entries(posicion, fecha, institucion, que, detalles, .protect = FALSE)
```

## R Shiny

```{r python-pkgs}
read_csv(file.path(data_path, "shiny.csv")) %>%
  tidyr::replace_na(list(fecha = " ", que = " ")) %>%
  detailed_entries(posicion, fecha, institucion, que, detalles, .protect = FALSE)
```

